/**
 * Sprint 3: TypeScript Type Definitions
 * SGA QA Pack - Job Assignment, Incidents, NCRs, Daily Summaries
 *
 * Created by: Worker #5 (Qwen 2.5 Coder)
 * Security: No sensitive data - template structures only
 * Reviewed by: Claude Sonnet 4.5
 */

// ============================================
// JOB MANAGEMENT
// ============================================

/**
 * Job assignment from Engineer to Foreman
 */
export interface Job {
  /** Unique job identifier (Dataverse GUID) */
  id: string;

  /** Job title/name */
  title: string;

  /** Detailed job description */
  description: string;

  /** Job site location/address */
  location: string;

  /** Foreman assigned to this job (user ID) */
  assignedForemanId: string;

  /** Foreman's display name */
  assignedForemanName?: string;

  /** Engineer who created the job (user ID) */
  engineerId: string;

  /** Engineer's display name */
  engineerName?: string;

  /** Job start date */
  startDate: Date;

  /** Job end date */
  endDate: Date;

  /** Current job status */
  status: 'pending' | 'in-progress' | 'completed' | 'cancelled';

  /** Date job was created */
  createdAt: Date;

  /** Date job was last modified */
  modifiedAt: Date;
}

/**
 * Request to create a new job
 */
export interface CreateJobRequest {
  title: string;
  description: string;
  location: string;
  assignedForemanId: string;
  startDate: string; // ISO 8601 format
  endDate: string;   // ISO 8601 format
}

/**
 * Response after creating a job
 */
export interface CreateJobResponse {
  success: boolean;
  jobId?: string;
  message: string;
  notificationSent?: boolean;
}

// ============================================
// DAILY SUMMARY (COPILOT)
// ============================================

/**
 * Request for Copilot daily summary
 */
export interface DailySummaryRequest {
  /** User requesting the summary (foreman ID) */
  userId: string;

  /** Date for the summary (defaults to today) */
  date?: Date;
}

/**
 * Response with Copilot-generated daily summary
 */
export interface DailySummaryResponse {
  /** Natural language summary generated by Copilot */
  summary: string;

  /** Jobs assigned for the specified date */
  jobsToday: Job[];

  /** Number of pending QA packs */
  pendingQAPacks: number;

  /** Upcoming deadlines (within 48 hours) */
  deadlines: JobDeadline[];

  /** Timestamp when summary was generated */
  generatedAt: string;

  /** Metadata about the generation */
  metadata: {
    tokensUsed: number;
    generationTime: number; // milliseconds
  };
}

/**
 * Job deadline information
 */
export interface JobDeadline {
  jobId: string;
  jobTitle: string;
  deadline: Date;
  hoursRemaining: number;
}

// ============================================
// INCIDENT REPORTING
// ============================================

/**
 * Incident report with Copilot-generated ID
 */
export interface IncidentReport {
  /** Dataverse record ID */
  id: string;

  /** Copilot-generated unique incident ID (format: INC-YYYYMMDD-XXXX) */
  incidentId: string;

  /** Incident description */
  description: string;

  /** Location where incident occurred */
  location: string;

  /** Incident severity level */
  severity: 'Low' | 'Medium' | 'High' | 'Critical';

  /** User who reported the incident */
  reportedBy: string;

  /** Reporter's display name */
  reportedByName?: string;

  /** Date and time incident was reported */
  reportedAt: Date;

  /** Photo URLs from SharePoint */
  photos: string[];

  /** Current incident status */
  status: 'open' | 'investigating' | 'resolved' | 'closed';

  /** Job ID if incident is related to a specific job */
  relatedJobId?: string;

  /** Investigation notes */
  investigationNotes?: string;

  /** User assigned to investigate */
  assignedTo?: string;

  /** Date incident was resolved */
  resolvedAt?: Date;
}

/**
 * Request to create a new incident report
 */
export interface CreateIncidentRequest {
  description: string;
  location: string;
  severity: 'Low' | 'Medium' | 'High' | 'Critical';
  relatedJobId?: string;
  photos?: File[]; // Photo files to upload
}

/**
 * Response after creating an incident
 */
export interface CreateIncidentResponse {
  success: boolean;
  incidentId?: string; // The Copilot-generated ID (INC-YYYYMMDD-XXXX)
  message: string;
  photoUploadResults?: PhotoUploadResult[];
}

/**
 * Result of photo upload
 */
export interface PhotoUploadResult {
  fileName: string;
  success: boolean;
  url?: string; // SharePoint URL if successful
  error?: string;
}

/**
 * Request to generate a unique incident ID
 */
export interface GenerateIncidentIDRequest {
  /** Date of the incident (defaults to today) */
  incidentDate?: Date;
}

/**
 * Response with generated incident ID
 */
export interface GenerateIncidentIDResponse {
  /** Generated incident ID (format: INC-YYYYMMDD-XXXX) */
  incidentId: string;

  /** Date used for ID generation */
  date: string;

  /** Sequential number for the day */
  sequenceNumber: number;
}

// ============================================
// NCR (NON-CONFORMANCE REPORT)
// ============================================

/**
 * Non-Conformance Report (NCR)
 */
export interface NCR {
  /** Dataverse record ID */
  id: string;

  /** Copilot-generated unique NCR ID (format: NCR-YYYYMMDD-XXXX) */
  ncrId: string;

  /** NCR description */
  description: string;

  /** Job ID this NCR is related to */
  jobId: string;

  /** Job title for reference */
  jobTitle?: string;

  /** Type of non-conformance */
  ncrType: 'material' | 'workmanship' | 'safety' | 'environmental' | 'other';

  /** Severity level */
  severity: 'Minor' | 'Major' | 'Critical';

  /** User who created the NCR (Engineer only) */
  createdBy: string;

  /** Creator's display name */
  createdByName?: string;

  /** Date NCR was created */
  createdAt: Date;

  /** Current NCR status */
  status: 'open' | 'under-review' | 'corrective-action-required' | 'closed';

  /** Corrective action required */
  correctiveAction?: string;

  /** User responsible for corrective action */
  assignedTo?: string;

  /** Target date for resolution */
  targetResolutionDate?: Date;

  /** Date NCR was closed */
  closedAt?: Date;

  /** Photos/evidence URLs */
  photos: string[];
}

/**
 * Request to create a new NCR
 */
export interface CreateNCRRequest {
  description: string;
  jobId: string;
  ncrType: 'material' | 'workmanship' | 'safety' | 'environmental' | 'other';
  severity: 'Minor' | 'Major' | 'Critical';
  correctiveAction?: string;
  assignedTo?: string;
  targetResolutionDate?: string; // ISO 8601 format
  photos?: File[];
}

/**
 * Response after creating an NCR
 */
export interface CreateNCRResponse {
  success: boolean;
  ncrId?: string; // The Copilot-generated ID (NCR-YYYYMMDD-XXXX)
  message: string;
  photoUploadResults?: PhotoUploadResult[];
}

/**
 * Request to generate a unique NCR ID
 */
export interface GenerateNCRIDRequest {
  /** Date of the NCR (defaults to today) */
  ncrDate?: Date;
}

/**
 * Response with generated NCR ID
 */
export interface GenerateNCRIDResponse {
  /** Generated NCR ID (format: NCR-YYYYMMDD-XXXX) */
  ncrId: string;

  /** Date used for ID generation */
  date: string;

  /** Sequential number for the day */
  sequenceNumber: number;
}

// ============================================
// QA PACK SUBMISSION
// ============================================

/**
 * QA Pack submission to Teams and SharePoint
 */
export interface QAPackSubmission {
  /** QA Pack ID from Dataverse */
  qaPackId: string;

  /** Job ID this QA pack belongs to */
  jobId: string;

  /** Job title for reference */
  jobTitle?: string;

  /** Foreman who submitted */
  submittedBy: string;

  /** Foreman's name */
  submittedByName?: string;

  /** Submission timestamp */
  submittedAt: Date;

  /** Generated PDF URL (SharePoint) */
  pdfUrl?: string;

  /** Teams message ID (for tracking) */
  teamsMessageId?: string;
}

/**
 * Request to submit a QA pack
 */
export interface SubmitQAPackRequest {
  /** QA Pack ID to submit */
  qaPackId: string;
}

/**
 * Response after QA pack submission
 */
export interface SubmitQAPackResponse {
  success: boolean;
  message: string;

  /** SharePoint URL where PDF was saved */
  sharePointUrl?: string;

  /** Teams channel where it was posted */
  teamsChannelPosted?: boolean;

  /** Any errors that occurred */
  errors?: string[];
}

// ============================================
// NOTIFICATIONS
// ============================================

/**
 * Job assignment notification
 */
export interface JobAssignmentNotification {
  /** Notification type */
  type: 'job-assignment';

  /** Job that was assigned */
  job: Job;

  /** Foreman who was assigned */
  foremanId: string;

  /** Teams Adaptive Card payload */
  adaptiveCard: any; // Adaptive Card JSON
}

/**
 * Incident notification
 */
export interface IncidentNotification {
  /** Notification type */
  type: 'incident-reported';

  /** Incident details */
  incident: IncidentReport;

  /** Users to notify (management) */
  notifyUsers: string[];

  /** Teams Adaptive Card payload */
  adaptiveCard: any; // Adaptive Card JSON
}

// ============================================
// DATAVERSE CONTEXT (for Copilot)
// ============================================

/**
 * User context from Dataverse for Copilot
 */
export interface DataverseContext {
  /** User's assigned jobs */
  userJobs: Job[];

  /** Recent QA packs submitted by user */
  recentQAPacks: QAPackSubmission[];

  /** User's open incidents */
  pendingIncidents: IncidentReport[];

  /** Upcoming deadlines */
  upcomingDeadlines: JobDeadline[];
}

// ============================================
// ERROR HANDLING
// ============================================

/**
 * Standard error response
 */
export interface ErrorResponse {
  success: false;
  error: {
    code: string;
    message: string;
    details?: any;
  };
  timestamp: string;
}

/**
 * API response wrapper (success or error)
 */
export type APIResponse<T> = T | ErrorResponse;

// ============================================
// UTILITY TYPES
// ============================================

/**
 * Pagination parameters
 */
export interface PaginationParams {
  page: number;
  pageSize: number;
}

/**
 * Paginated response
 */
export interface PaginatedResponse<T> {
  data: T[];
  pagination: {
    currentPage: number;
    pageSize: number;
    totalPages: number;
    totalRecords: number;
  };
}

/**
 * Filter options for queries
 */
export interface FilterOptions {
  startDate?: Date;
  endDate?: Date;
  status?: string;
  assignedTo?: string;
}
