import React from 'react';
import { SamplingPlan } from '../../types';
import SgaLogo from './SgaLogo.js';

const Detail: React.FC<{ label: string; value?: React.ReactNode }> = ({ label, value }) => (
    React.createElement('div', null,
        React.createElement('p', { style: { fontSize: '8pt', fontWeight: 700, color: '#6b7280', textTransform: 'uppercase', marginBottom: '2px' } }, label),
        React.createElement('p', { style: { fontSize: '10pt' } }, value || '---')
    )
);

const SamplingPlanPrintView: React.FC<{ plan: SamplingPlan }> = ({ plan }) => {
    return (
        React.createElement('div', { style: { fontFamily: '"Helvetica Neue", Helvetica, Arial, sans-serif', fontSize: '10pt' } },
             React.createElement('style', null, `
              body { -webkit-print-color-adjust: exact; }
              .table { width: 100%; border-collapse: collapse; font-size: 9pt; margin-top: 24px; }
              .th { background-color: #f3f4f6; text-align: left; padding: 8px 10px; border: 1px solid #d1d5db; font-weight: 700; }
              .td { padding: 8px 10px; border: 1px solid #e5e7eb; vertical-align: top; }
            `),
            
            React.createElement('header', { style: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '24px', borderBottom: '2px solid #e5e7eb', paddingBottom: '16px' } },
                React.createElement('div', null,
                    React.createElement(SgaLogo, { className: "h-12 w-auto" }),
                    React.createElement('h1', { style: { fontSize: '20pt', fontWeight: 700, marginTop: '8px', color: '#1f2937' } }, "Stratified Random Sample Locations")
                ),
                React.createElement('div', { style: { textAlign: 'right', fontSize: '9pt' } },
                    React.createElement('p', null, React.createElement('strong', null, 'Job Number:'), ` ${plan.jobNo}`),
                    React.createElement('p', null, React.createElement('strong', null, 'Lot Number:'), ` ${plan.lotNo}`)
                )
            ),

            React.createElement('div', { style: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '16px', marginBottom: '24px' } },
                React.createElement(Detail, { label: "Specification / Method", value: plan.specification }),
                React.createElement(Detail, { label: "Lot Dimensions", value: `CH ${plan.startChainage}m to CH ${plan.endChainage}m` }),
                React.createElement(Detail, { label: "Generated By", value: plan.generatedBy }),
                React.createElement(Detail, { label: "Date Generated", value: new Date(plan.timestamp).toLocaleDateString('en-AU') })
            ),

            React.createElement('table', { className: "table" },
                React.createElement('thead', null,
                    React.createElement('tr', null,
                        React.createElement('th', { className: "th", style: { width: '15%' } }, 'Sample #'),
                        React.createElement('th', { className: "th", style: { width: '25%' } }, 'Chainage (m)'),
                        React.createElement('th', { className: "th", style: { width: '25%' } }, 'Transverse Offset'),
                        React.createElement('th', { className: "th", style: { width: '35%' } }, 'Notes / Result')
                    )
                ),
                React.createElement('tbody', null,
                    plan.results.map((res, i) => (
                        React.createElement('tr', { key: i },
                            React.createElement('td', { className: "td" }, i + 1),
                            React.createElement('td', { className: "td" }, res.chainage.toFixed(2)),
                            React.createElement('td', { className: "td" }, res.offset),
                            React.createElement('td', { className: "td", style: { height: '40px' } })
                        )
                    ))
                )
            )
        )
    );
};

export default SamplingPlanPrintView;
