// components/dashboard/DailyBriefing.tsx

import React, { useState } from 'react';

export interface DailyBriefingProps {
  summary: string | null;
  loading?: boolean;
  error?: string | null;
  onRefresh?: () => void;
}

const DailyBriefing: React.FC<DailyBriefingProps> = ({
  summary,
  loading = false,
  error = null,
  onRefresh
}) => {
  const [isExpanded, setIsExpanded] = useState(true);

  const toggleExpanded = () => {
    setIsExpanded(!isExpanded);
  };

  if (loading) {
    return (
      <div className="bg-gradient-to-r from-sga-700 to-sga-600 rounded-lg shadow p-6 text-white">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center">
            <span className="text-2xl mr-3" role="img" aria-label="Briefing">
              📋
            </span>
            <h3 className="text-lg font-semibold">Daily Briefing</h3>
          </div>
        </div>
        <div className="animate-pulse space-y-3">
          <div className="h-4 bg-white/20 rounded w-full"></div>
          <div className="h-4 bg-white/20 rounded w-5/6"></div>
          <div className="h-4 bg-white/20 rounded w-4/6"></div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="bg-gradient-to-r from-red-600 to-red-700 rounded-lg shadow p-6 text-white">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center">
            <span className="text-2xl mr-3" role="img" aria-label="Error">
              ⚠️
            </span>
            <h3 className="text-lg font-semibold">Daily Briefing</h3>
          </div>
          {onRefresh && (
            <button
              onClick={onRefresh}
              className="px-3 py-1.5 text-sm bg-white/10 hover:bg-white/20 rounded-lg transition-colors min-h-touch"
              aria-label="Refresh briefing"
            >
              Retry
            </button>
          )}
        </div>
        <p className="text-white/90 text-sm">
          {error || 'Failed to load daily briefing. Please try again.'}
        </p>
      </div>
    );
  }

  if (!summary) {
    return (
      <div className="bg-gradient-to-r from-gray-600 to-gray-700 rounded-lg shadow p-6 text-white">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center">
            <span className="text-2xl mr-3" role="img" aria-label="Briefing">
              📋
            </span>
            <h3 className="text-lg font-semibold">Daily Briefing</h3>
          </div>
          {onRefresh && (
            <button
              onClick={onRefresh}
              className="px-3 py-1.5 text-sm bg-white/10 hover:bg-white/20 rounded-lg transition-colors min-h-touch"
              aria-label="Refresh briefing"
            >
              Refresh
            </button>
          )}
        </div>
        <p className="text-white/90 text-sm">
          No briefing available. Check back later for your daily summary.
        </p>
      </div>
    );
  }

  return (
    <div className="bg-gradient-to-r from-sga-700 to-sga-600 rounded-lg shadow p-6 text-white">
      <div className="flex items-center justify-between mb-4">
        <button
          onClick={toggleExpanded}
          className="flex items-center flex-1 text-left min-h-touch"
          aria-expanded={isExpanded}
          aria-controls="briefing-content"
        >
          <span className="text-2xl mr-3" role="img" aria-label="Briefing">
            📋
          </span>
          <h3 className="text-lg font-semibold">Daily Briefing</h3>
          <span className="ml-2 text-lg transition-transform" style={{ transform: isExpanded ? 'rotate(180deg)' : 'rotate(0deg)' }}>
            ▼
          </span>
        </button>
        {onRefresh && (
          <button
            onClick={onRefresh}
            className="px-3 py-1.5 text-sm bg-white/10 hover:bg-white/20 rounded-lg transition-colors ml-4 min-h-touch"
            aria-label="Refresh briefing"
          >
            <span className="mr-1">🔄</span> Refresh
          </button>
        )}
      </div>

      {isExpanded && (
        <div
          id="briefing-content"
          className="prose prose-invert max-w-none"
          style={{
            animation: 'slideDown 0.3s ease-out'
          }}
        >
          <div className="text-white/90 text-sm leading-relaxed whitespace-pre-wrap">
            {summary}
          </div>
          <div className="mt-4 pt-4 border-t border-white/20">
            <p className="text-xs text-white/60">
              Generated by AI • Updates daily at midnight
            </p>
          </div>
        </div>
      )}
    </div>
  );
};

export default DailyBriefing;
