# Create-DataverseTables-PAC.ps1
# Generated by Gemini AI with supervision from Claude
# Creates all 12 Dataverse tables for SGA QA Pack

# Ensure you are logged in and have the correct environment selected
# pac auth list
# pac auth select --index <index of your desired environment>

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Creating 12 Dataverse Tables" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "This will create all tables for SGA QA Pack" -ForegroundColor Yellow
Write-Host "Estimated time: 30-45 minutes" -ForegroundColor Yellow
Write-Host ""

$confirm = Read-Host "Continue? (yes/no)"
if ($confirm -ne "yes") {
    Write-Host "Cancelled." -ForegroundColor Yellow
    exit
}

# ================================================================================
# sga_job Table and Columns
# ================================================================================

Write-Host "`n[1/12] Creating sga_job table..." -ForegroundColor Cyan
pac dataverse create --entity sga_job --display-name "Job" --plural-name "Jobs" --description "Construction jobs"

Write-Host "  Adding columns..." -ForegroundColor Gray
pac dataverse create-column --entity sga_job --column jobnumber --data-type text --display-name "Job Number" --required-behavior applicationrequired
pac dataverse create-column --entity sga_job --column jobname --data-type text --display-name "Job Name"
pac dataverse create-column --entity sga_job --column startdate --data-type dateonly --display-name "Start Date"
pac dataverse create-column --entity sga_job --column enddate --data-type dateonly --display-name "End Date"
pac dataverse create-column --entity sga_job --column location --data-type text --display-name "Location"
pac dataverse create-column --entity sga_job --column foremanid --data-type lookup --display-name "Foreman" --target sga_foreman
pac dataverse create-column --entity sga_job --column itptemplateid --data-type lookup --display-name "ITP Template" --target sga_itptemplate
pac dataverse create-column --entity sga_job --column status --data-type picklist --display-name "Status" --picklist-values "Planned,InProgress,Completed,OnHold"
pac dataverse create-column --entity sga_job --column notes --data-type memo --display-name "Notes"
Write-Host "  ✅ sga_job complete" -ForegroundColor Green

# ================================================================================
# sga_foreman Table and Columns
# ================================================================================

Write-Host "`n[2/12] Creating sga_foreman table..." -ForegroundColor Cyan
pac dataverse create --entity sga_foreman --display-name "Foreman" --plural-name "Foremen" --description "Construction foremen"

Write-Host "  Adding columns..." -ForegroundColor Gray
pac dataverse create-column --entity sga_foreman --column firstname --data-type text --display-name "First Name" --required-behavior applicationrequired
pac dataverse create-column --entity sga_foreman --column lastname --data-type text --display-name "Last Name" --required-behavior applicationrequired
pac dataverse create-column --entity sga_foreman --column email --data-type email --display-name "Email"
pac dataverse create-column --entity sga_foreman --column phone --data-type phone --display-name "Phone"
pac dataverse create-column --entity sga_foreman --column division --data-type text --display-name "Division"
Write-Host "  ✅ sga_foreman complete" -ForegroundColor Green

# ================================================================================
# sga_qapack Table and Columns
# ================================================================================

Write-Host "`n[3/12] Creating sga_qapack table..." -ForegroundColor Cyan
pac dataverse create --entity sga_qapack --display-name "QA Pack" --plural-name "QA Packs" --description "Quality assurance packs"

Write-Host "  Adding columns..." -ForegroundColor Gray
pac dataverse create-column --entity sga_qapack --column jobid --data-type lookup --display-name "Job" --target sga_job --required-behavior applicationrequired
pac dataverse create-column --entity sga_qapack --column qapacknumber --data-type text --display-name "QA Pack Number" --required-behavior applicationrequired
pac dataverse create-column --entity sga_qapack --column createddate --data-type datetime --display-name "Created Date" --format dateonly
pac dataverse create-column --entity sga_qapack --column submitteddate --data-type datetime --display-name "Submitted Date" --format dateonly
pac dataverse create-column --entity sga_qapack --column status --data-type picklist --display-name "Status" --picklist-values "Draft,Submitted,Approved,Rejected"
pac dataverse create-column --entity sga_qapack --column notes --data-type memo --display-name "Notes"
pac dataverse create-column --entity sga_qapack --column aisummary --data-type memo --display-name "AI Summary"
Write-Host "  ✅ sga_qapack complete" -ForegroundColor Green

# ================================================================================
# sga_dailyreport Table and Columns
# ================================================================================

Write-Host "`n[4/12] Creating sga_dailyreport table..." -ForegroundColor Cyan
pac dataverse create --entity sga_dailyreport --display-name "Daily Report" --plural-name "Daily Reports" --description "Daily foreman reports"

Write-Host "  Adding columns..." -ForegroundColor Gray
pac dataverse create-column --entity sga_dailyreport --column qapackid --data-type lookup --display-name "QA Pack" --target sga_qapack --required-behavior applicationrequired
pac dataverse create-column --entity sga_dailyreport --column reportdate --data-type dateonly --display-name "Report Date" --required-behavior applicationrequired
pac dataverse create-column --entity sga_dailyreport --column weather --data-type text --display-name "Weather"
pac dataverse create-column --entity sga_dailyreport --column manpower --data-type integer --display-name "Manpower"
pac dataverse create-column --entity sga_dailyreport --column equipment --data-type text --display-name "Equipment"
pac dataverse create-column --entity sga_dailyreport --column notes --data-type memo --display-name "Notes"
Write-Host "  ✅ sga_dailyreport complete" -ForegroundColor Green

# ================================================================================
# sga_incident Table and Columns
# ================================================================================

Write-Host "`n[5/12] Creating sga_incident table..." -ForegroundColor Cyan
pac dataverse create --entity sga_incident --display-name "Incident" --plural-name "Incidents" --description "Incident reports"

Write-Host "  Adding columns..." -ForegroundColor Gray
pac dataverse create-column --entity sga_incident --column jobid --data-type lookup --display-name "Job" --target sga_job --required-behavior applicationrequired
pac dataverse create-column --entity sga_incident --column incidentnumber --data-type text --display-name "Incident Number" --required-behavior applicationrequired
pac dataverse create-column --entity sga_incident --column incidentdate --data-type datetime --display-name "Incident Date" --format dateonly
pac dataverse create-column --entity sga_incident --column description --data-type memo --display-name "Description"
pac dataverse create-column --entity sga_incident --column severity --data-type picklist --display-name "Severity" --picklist-values "Minor,Moderate,Serious,Critical"
pac dataverse create-column --entity sga_incident --column status --data-type picklist --display-name "Status" --picklist-values "Open,Investigating,Closed"
pac dataverse create-column --entity sga_incident --column notes --data-type memo --display-name "Notes"
pac dataverse create-column --entity sga_incident --column resolution --data-type memo --display-name "Resolution"
Write-Host "  ✅ sga_incident complete" -ForegroundColor Green

# ================================================================================
# sga_ncr Table and Columns
# ================================================================================

Write-Host "`n[6/12] Creating sga_ncr table..." -ForegroundColor Cyan
pac dataverse create --entity sga_ncr --display-name "NCR" --plural-name "NCRs" --description "Non-conformance reports"

Write-Host "  Adding columns..." -ForegroundColor Gray
pac dataverse create-column --entity sga_ncr --column jobid --data-type lookup --display-name "Job" --target sga_job --required-behavior applicationrequired
pac dataverse create-column --entity sga_ncr --column ncrnumber --data-type text --display-name "NCR Number" --required-behavior applicationrequired
pac dataverse create-column --entity sga_ncr --column raiseddate --data-type datetime --display-name "Raised Date" --format dateonly
pac dataverse create-column --entity sga_ncr --column description --data-type memo --display-name "Description"
pac dataverse create-column --entity sga_ncr --column cause --data-type memo --display-name "Cause"
pac dataverse create-column --entity sga_ncr --column correctiveaction --data-type memo --display-name "Corrective Action"
pac dataverse create-column --entity sga_ncr --column status --data-type picklist --display-name "Status" --picklist-values "Open,PendingApproval,Closed"
pac dataverse create-column --entity sga_ncr --column notes --data-type memo --display-name "Notes"
pac dataverse create-column --entity sga_ncr --column duedate --data-type dateonly --display-name "Due Date"
Write-Host "  ✅ sga_ncr complete" -ForegroundColor Green

# ================================================================================
# sga_samplingplan Table and Columns
# ================================================================================

Write-Host "`n[7/12] Creating sga_samplingplan table..." -ForegroundColor Cyan
pac dataverse create --entity sga_samplingplan --display-name "Sampling Plan" --plural-name "Sampling Plans" --description "Sampling plans for quality control"

Write-Host "  Adding columns..." -ForegroundColor Gray
pac dataverse create-column --entity sga_samplingplan --column planname --data-type text --display-name "Plan Name" --required-behavior applicationrequired
pac dataverse create-column --entity sga_samplingplan --column description --data-type memo --display-name "Description"
pac dataverse create-column --entity sga_samplingplan --column samplesize --data-type integer --display-name "Sample Size"
pac dataverse create-column --entity sga_samplingplan --column frequency --data-type text --display-name "Frequency"
pac dataverse create-column --entity sga_samplingplan --column method --data-type text --display-name "Method"
pac dataverse create-column --entity sga_samplingplan --column notes --data-type memo --display-name "Notes"
Write-Host "  ✅ sga_samplingplan complete" -ForegroundColor Green

# ================================================================================
# sga_resource Table and Columns
# ================================================================================

Write-Host "`n[8/12] Creating sga_resource table..." -ForegroundColor Cyan
pac dataverse create --entity sga_resource --display-name "Resource" --plural-name "Resources" --description "Construction resources (equipment, materials)"

Write-Host "  Adding columns..." -ForegroundColor Gray
pac dataverse create-column --entity sga_resource --column resourcename --data-type text --display-name "Resource Name" --required-behavior applicationrequired
pac dataverse create-column --entity sga_resource --column resourcetype --data-type picklist --display-name "Resource Type" --picklist-values "Equipment,Material,Labor"
pac dataverse create-column --entity sga_resource --column quantity --data-type decimal --display-name "Quantity"
pac dataverse create-column --entity sga_resource --column unitofmeasure --data-type text --display-name "Unit of Measure"
pac dataverse create-column --entity sga_resource --column notes --data-type memo --display-name "Notes"
Write-Host "  ✅ sga_resource complete" -ForegroundColor Green

# ================================================================================
# sga_itptemplate Table and Columns
# ================================================================================

Write-Host "`n[9/12] Creating sga_itptemplate table..." -ForegroundColor Cyan
pac dataverse create --entity sga_itptemplate --display-name "ITP Template" --plural-name "ITP Templates" --description "Inspection Test Plan Templates"

Write-Host "  Adding columns..." -ForegroundColor Gray
pac dataverse create-column --entity sga_itptemplate --column templatename --data-type text --display-name "Template Name" --required-behavior applicationrequired
pac dataverse create-column --entity sga_itptemplate --column description --data-type memo --display-name "Description"
pac dataverse create-column --entity sga_itptemplate --column version --data-type text --display-name "Version"
pac dataverse create-column --entity sga_itptemplate --column createddate --data-type datetime --display-name "Created Date" --format dateonly
pac dataverse create-column --entity sga_itptemplate --column notes --data-type memo --display-name "Notes"
Write-Host "  ✅ sga_itptemplate complete" -ForegroundColor Green

# ================================================================================
# sga_sitephoto Table and Columns
# ================================================================================

Write-Host "`n[10/12] Creating sga_sitephoto table..." -ForegroundColor Cyan
pac dataverse create --entity sga_sitephoto --display-name "Site Photo" --plural-name "Site Photos" --description "Field site photographs"

Write-Host "  Adding columns..." -ForegroundColor Gray
pac dataverse create-column --entity sga_sitephoto --column qapackid --data-type lookup --display-name "QA Pack" --target sga_qapack --required-behavior applicationrequired
pac dataverse create-column --entity sga_sitephoto --column phototaken --data-type datetime --display-name "Photo Taken" --format dateonly
pac dataverse create-column --entity sga_sitephoto --column description --data-type memo --display-name "Description"
pac dataverse create-column --entity sga_sitephoto --column photoname --data-type text --display-name "Photo Name"
pac dataverse create-column --entity sga_sitephoto --column photolocation --data-type text --display-name "Photo Location"
pac dataverse create-column --entity sga_sitephoto --column photofile --data-type file --display-name "Photo File"
Write-Host "  ✅ sga_sitephoto complete" -ForegroundColor Green

# ================================================================================
# sga_asphaltplacement Table and Columns
# ================================================================================

Write-Host "`n[11/12] Creating sga_asphaltplacement table..." -ForegroundColor Cyan
pac dataverse create --entity sga_asphaltplacement --display-name "Asphalt Placement" --plural-name "Asphalt Placements" --description "Asphalt placement records"

Write-Host "  Adding columns..." -ForegroundColor Gray
pac dataverse create-column --entity sga_asphaltplacement --column qapackid --data-type lookup --display-name "QA Pack" --target sga_qapack --required-behavior applicationrequired
pac dataverse create-column --entity sga_asphaltplacement --column placementdate --data-type datetime --display-name "Placement Date" --format dateonly
pac dataverse create-column --entity sga_asphaltplacement --column asphaltmix --data-type text --display-name "Asphalt Mix"
pac dataverse create-column --entity sga_asphaltplacement --column temperature --data-type decimal --display-name "Temperature"
pac dataverse create-column --entity sga_asphaltplacement --column area --data-type text --display-name "Area"
pac dataverse create-column --entity sga_asphaltplacement --column notes --data-type memo --display-name "Notes"
Write-Host "  ✅ sga_asphaltplacement complete" -ForegroundColor Green

# ================================================================================
# sga_straightedgereport Table and Columns
# ================================================================================

Write-Host "`n[12/12] Creating sga_straightedgereport table..." -ForegroundColor Cyan
pac dataverse create --entity sga_straightedgereport --display-name "Straight Edge Report" --plural-name "Straight Edge Reports" --description "Straight edge reports"

Write-Host "  Adding columns..." -ForegroundColor Gray
pac dataverse create-column --entity sga_straightedgereport --column qapackid --data-type lookup --display-name "QA Pack" --target sga_qapack --required-behavior applicationrequired
pac dataverse create-column --entity sga_straightedgereport --column reportdate --data-type datetime --display-name "Report Date" --format dateonly
pac dataverse create-column --entity sga_straightedgereport --column location --data-type text --display-name "Location"
pac dataverse create-column --entity sga_straightedgereport --column deviation --data-type decimal --display-name "Deviation"
pac dataverse create-column --entity sga_straightedgereport --column result --data-type picklist --display-name "Result" --picklist-values "Pass,Fail"
pac dataverse create-column --entity sga_straightedgereport --column notes --data-type memo --display-name "Notes"
Write-Host "  ✅ sga_straightedgereport complete" -ForegroundColor Green

Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "ALL TABLES CREATED SUCCESSFULLY!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "✅ 12 tables created" -ForegroundColor Green
Write-Host "✅ All columns configured" -ForegroundColor Green
Write-Host ""
Write-Host "Next: Run .\scripts\Create-SharePointLibraries.ps1" -ForegroundColor Yellow
